// Mocks generated by Mockito 5.4.5 from annotations
// in strichpunkt/test/features/user_profiles/data/repositories/user_profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:strichpunkt/core/network/network_info.dart' as _i6;
import 'package:strichpunkt/features/user_profiles/data/datasources/user_profile_local_data_source.dart'
    as _i5;
import 'package:strichpunkt/features/user_profiles/data/datasources/user_profile_remote_data_source.dart'
    as _i2;
import 'package:strichpunkt/features/user_profiles/domain/entities/user_profile.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRemoteDataSource extends _i1.Mock
    implements _i2.UserProfileRemoteDataSource {
  MockUserProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserProfile>> getUserProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfiles, []),
            returnValue: _i3.Future<List<_i4.UserProfile>>.value(
              <_i4.UserProfile>[],
            ),
          )
          as _i3.Future<List<_i4.UserProfile>>);
}

/// A class which mocks [UserProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileLocalDataSource extends _i1.Mock
    implements _i5.UserProfileLocalDataSource {
  MockUserProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserProfile>> getUserProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfiles, []),
            returnValue: _i3.Future<List<_i4.UserProfile>>.value(
              <_i4.UserProfile>[],
            ),
          )
          as _i3.Future<List<_i4.UserProfile>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
